spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Stronglover
          jwk-set-uri: http://localhost:8080/realms/Stronglover/protocol/openid-connect/certs
server:
  port: 8085
jwt:
  auth:
    converter:
      resource-id: Stronglover-rest-api
      principle-attribute: preferred_username